### ISSUE TITLE
Text bug

### ISSUE THREAD

**Issue by ModMaker101** [Bedrock-OSS/bedrock-wiki-vite#675] opened 2023-07-15 14:13 UTC
Issue: The text on the custom armor page is not colored

Affected pages: It's harder to read and see where the content doesn't work and so I can read it and use it

Suggestions: Figure out what isn't working and fix it

**Comment by QuazChick** [comment] 2023-07-19 18:26
Duplicate of #383

**Closed as completed** 2023-12-29 20:40 UTC
Labels: BUG
